# 기본 설정: 모든 프로파일에서 공통으로 사용되는 설정
spring:
  profiles:
    default: local  # 기본 프로파일을 'local'로 설정

  datasource:
    url: jdbc:h2:mem:cafeKioskApplication  # H2 메모리 데이터베이스 URL
    driver-class-name: org.h2.Driver  # H2 드라이버
    username: sa  # 기본 사용자명
    password:  # 비밀번호를 설정하지 않음 (개발 환경에서만 사용)

  jpa:
    hibernate:
      ddl-auto: none  # Hibernate가 자동으로 테이블을 생성하지 않도록 설정
    show-sql: false  # SQL 쿼리 로그 출력 안 함 (기본값)
    properties:
      hibernate:
        format_sql: true  # SQL 로그 포맷팅

# 'local' 프로파일: 개발 환경에서 사용할 설정
---
spring:
  config:
    activate:
      on-profile: local  # local 프로파일에서 활성화

  datasource:
    url: jdbc:h2:mem:cafeKioskApplication  # H2 메모리 데이터베이스 URL
    driver-class-name: org.h2.Driver  # H2 드라이버
    username: sa  # 기본 사용자명
    password:  # 비밀번호를 설정하지 않음 (개발 환경에서만 사용)

  jpa:
    hibernate:
      ddl-auto: create  # 애플리케이션 실행 시마다 테이블 생성
    show-sql: true  # SQL 쿼리 로그 출력
    properties:
      hibernate:
        format_sql: true  # SQL 로그 포맷팅
    defer-datasource-initialization: true  # Hibernate 초기화 이후 data.sql 실행

  h2:
    console:
      enabled: true  # H2 콘솔 활성화 (http://localhost:8080/h2-console에서 접근 가능)

# 'test' 프로파일: 테스트 환경에서 사용할 설정
---
spring:
  config:
    activate:
      on-profile: test  # test 프로파일에서 활성화

  datasource:
    url: jdbc:h2:mem:cafeKioskApplication  # H2 메모리 데이터베이스 URL
    driver-class-name: org.h2.Driver  # H2 드라이버
    username: sa  # 기본 사용자명
    password:  # 비밀번호를 설정하지 않음 (테스트 환경에서만 사용)

  jpa:
    hibernate:
      ddl-auto: create  # 애플리케이션 실행 시마다 테이블 생성
    show-sql: true  # SQL 쿼리 로그 출력
    properties:
      hibernate:
        format_sql: true  # SQL 로그 포맷팅
    database-platform: org.hibernate.dialect.H2Dialect  # H2Dialect 설정

  sql:
    init:
      mode: never  # SQL 초기화 스크립트 실행 안 함

# 로깅 설정: Hibernate SQL 및 바인딩 로그 레벨 설정
logging:
  level:
    org.hibernate.SQL: debug  # Hibernate SQL 쿼리 로그를 디버그 수준으로 출력
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # Hibernate 바인딩 로그를 트레이스 수준으로 출력
